// file: TuriSMAOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologia;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: TuriSMAOntology.java
 * @author ontology bean generator
 * @version 2019/08/2, 23:50:21
 */
public class TuriSMAOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "turiSMA";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new TuriSMAOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String REGISTRARCARACTERISTICASDELHOTEL_AGENTEHOTEL="agenteHotel";
    public static final String REGISTRARCARACTERISTICASDELHOTEL_HOTEL="hotel";
    public static final String REGISTRARCARACTERISTICASDELHOTEL_AGENTESISTEMA="agenteSistema";
    public static final String REGISTRARCARACTERISTICASDELHOTEL="RegistrarCaracteristicasDelHotel";
    public static final String RESERVARHOTEL_AGENTEHOTEL="agenteHotel";
    public static final String RESERVARHOTEL_HOTEL="hotel";
    public static final String RESERVARHOTEL_AGENTESISTEMA="agenteSistema";
    public static final String RESERVARHOTEL_CLIENTE="cliente";
    public static final String RESERVARHOTEL="ReservarHotel";
    public static final String INSCRIBIRHOTELES_AGENTEHOTEL="agenteHotel";
    public static final String INSCRIBIRHOTELES_HOTEL="hotel";
    public static final String INSCRIBIRHOTELES_AGENTESISTEMA="agenteSistema";
    public static final String INSCRIBIRHOTELES="InscribirHoteles";
    public static final String REGISTRARPERFILDELCLIENTE_AGENTECLIENTE="agenteCliente";
    public static final String REGISTRARPERFILDELCLIENTE_AGENTESISTEMA="agenteSistema";
    public static final String REGISTRARPERFILDELCLIENTE_CLIENTE="cliente";
    public static final String REGISTRARPERFILDELCLIENTE="RegistrarPerfilDelCliente";
    public static final String AGENTERESERVAS_SEGUIMIENTODEUNARESERVA="SeguimientoDeUnaReserva";
    public static final String AGENTERESERVAS_CAMBIODEUNARESERVA="CambioDeUnaReserva";
    public static final String AGENTERESERVAS="AgenteReservas";
    public static final String AGENTEHOTELES_CARACTERISTICADELHOTEL="CaracteristicaDelHotel";
    public static final String AGENTEHOTELES_INFORMACIONDELHOTEL="InformacionDelHotel";
    public static final String AGENTEHOTELES="AgenteHoteles";
    public static final String AGENTECLIENTES_INFORMACIONDELCLIENTE="InformacionDelCliente";
    public static final String AGENTECLIENTES="AgenteClientes";
    public static final String AGENTESISTEMA_INFORMACIONDELCLIENTE="InformacionDelCliente";
    public static final String AGENTESISTEMA_INFORMACIONDELHOTEL="InformacionDelHotel";
    public static final String AGENTESISTEMA="AgenteSistema";
    public static final String HOTELESPOTENCIALES_MENSAJE="mensaje";
    public static final String HOTELESPOTENCIALES="HotelesPotenciales";
    public static final String CONFIRMACIÓNCAMBIODERESERVA_MENSAJE="mensaje";
    public static final String CONFIRMACIÓNCAMBIODERESERVA="ConfirmaciónCambiodeReserva";
    public static final String CANCELACIONEXITOSA_MENSAJE="mensaje";
    public static final String CANCELACIONEXITOSA="CancelacionExitosa";
    public static final String ENTREGADEINFORMACION_MENSAJE="mensaje";
    public static final String ENTREGADEINFORMACION="EntregaDeInformacion";
    public static final String RESERVA_HOTEL="hotel";
    public static final String RESERVA_NUMEROHABITACION="NumeroHabitacion";
    public static final String RESERVA_CLIENTE="cliente";
    public static final String RESERVA="Reserva";
    public static final String HOTEL_TELEFONO="Telefono";
    public static final String HOTEL_CALIFICACION="Calificacion";
    public static final String HOTEL_NIVELDESEGURIDAD="NivelDeSeguridad";
    public static final String HOTEL_CAFETERIASYRESTAURANTES="CafeteriasyRestaurantes";
    public static final String HOTEL_TARIFAS="Tarifas";
    public static final String HOTEL_DIRECCION="Direccion";
    public static final String HOTEL_CERTIFICACIÓNDEIDIOMAS="CertificaciónDeIdiomas";
    public static final String HOTEL_NOMBREHOTEL="NombreHotel";
    public static final String HOTEL="Hotel";
    public static final String CLIENTE_PREFERENCIAS="Preferencias";
    public static final String CLIENTE_PRESUPUESTO="Presupuesto";
    public static final String CLIENTE_CEDULA="Cedula";
    public static final String CLIENTE_NOMBRE="Nombre";
    public static final String CLIENTE="Cliente";

  /**
   * Constructor
  */
  private TuriSMAOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema clienteSchema = new ConceptSchema(CLIENTE);
    add(clienteSchema, ontologia.Cliente.class);
    ConceptSchema hotelSchema = new ConceptSchema(HOTEL);
    add(hotelSchema, ontologia.Hotel.class);
    ConceptSchema reservaSchema = new ConceptSchema(RESERVA);
    add(reservaSchema, ontologia.Reserva.class);

    // adding AgentAction(s)
    AgentActionSchema entregaDeInformacionSchema = new AgentActionSchema(ENTREGADEINFORMACION);
    add(entregaDeInformacionSchema, ontologia.EntregaDeInformacion.class);
    AgentActionSchema cancelacionExitosaSchema = new AgentActionSchema(CANCELACIONEXITOSA);
    add(cancelacionExitosaSchema, ontologia.CancelacionExitosa.class);
    AgentActionSchema confirmaciónCambiodeReservaSchema = new AgentActionSchema(CONFIRMACIÓNCAMBIODERESERVA);
    add(confirmaciónCambiodeReservaSchema, ontologia.ConfirmaciónCambiodeReserva.class);
    AgentActionSchema hotelesPotencialesSchema = new AgentActionSchema(HOTELESPOTENCIALES);
    add(hotelesPotencialesSchema, ontologia.HotelesPotenciales.class);

    // adding AID(s)
    ConceptSchema agenteSistemaSchema = new ConceptSchema(AGENTESISTEMA);
    add(agenteSistemaSchema, ontologia.AgenteSistema.class);
    ConceptSchema agenteClientesSchema = new ConceptSchema(AGENTECLIENTES);
    add(agenteClientesSchema, ontologia.AgenteClientes.class);
    ConceptSchema agenteHotelesSchema = new ConceptSchema(AGENTEHOTELES);
    add(agenteHotelesSchema, ontologia.AgenteHoteles.class);
    ConceptSchema agenteReservasSchema = new ConceptSchema(AGENTERESERVAS);
    add(agenteReservasSchema, ontologia.AgenteReservas.class);

    // adding Predicate(s)
    PredicateSchema registrarPerfilDelClienteSchema = new PredicateSchema(REGISTRARPERFILDELCLIENTE);
    add(registrarPerfilDelClienteSchema, ontologia.RegistrarPerfilDelCliente.class);
    PredicateSchema inscribirHotelesSchema = new PredicateSchema(INSCRIBIRHOTELES);
    add(inscribirHotelesSchema, ontologia.InscribirHoteles.class);
    PredicateSchema reservarHotelSchema = new PredicateSchema(RESERVARHOTEL);
    add(reservarHotelSchema, ontologia.ReservarHotel.class);
    PredicateSchema registrarCaracteristicasDelHotelSchema = new PredicateSchema(REGISTRARCARACTERISTICASDELHOTEL);
    add(registrarCaracteristicasDelHotelSchema, ontologia.RegistrarCaracteristicasDelHotel.class);


    // adding fields
    clienteSchema.add(CLIENTE_NOMBRE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    clienteSchema.add(CLIENTE_CEDULA, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    clienteSchema.add(CLIENTE_PRESUPUESTO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.OPTIONAL);
    clienteSchema.add(CLIENTE_PREFERENCIAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_NOMBREHOTEL, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_CERTIFICACIÓNDEIDIOMAS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_DIRECCION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_TARIFAS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_CAFETERIASYRESTAURANTES, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_NIVELDESEGURIDAD, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_CALIFICACION, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    hotelSchema.add(HOTEL_TELEFONO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    reservaSchema.add(RESERVA_CLIENTE, clienteSchema, ObjectSchema.OPTIONAL);
    reservaSchema.add(RESERVA_NUMEROHABITACION, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    reservaSchema.add(RESERVA_HOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    entregaDeInformacionSchema.add(ENTREGADEINFORMACION_MENSAJE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    cancelacionExitosaSchema.add(CANCELACIONEXITOSA_MENSAJE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    confirmaciónCambiodeReservaSchema.add(CONFIRMACIÓNCAMBIODERESERVA_MENSAJE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    hotelesPotencialesSchema.add(HOTELESPOTENCIALES_MENSAJE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    agenteSistemaSchema.add(AGENTESISTEMA_INFORMACIONDELHOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    agenteSistemaSchema.add(AGENTESISTEMA_INFORMACIONDELCLIENTE, clienteSchema, ObjectSchema.OPTIONAL);
    agenteClientesSchema.add(AGENTECLIENTES_INFORMACIONDELCLIENTE, clienteSchema, ObjectSchema.OPTIONAL);
    agenteHotelesSchema.add(AGENTEHOTELES_INFORMACIONDELHOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    agenteHotelesSchema.add(AGENTEHOTELES_CARACTERISTICADELHOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    agenteReservasSchema.add(AGENTERESERVAS_CAMBIODEUNARESERVA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    agenteReservasSchema.add(AGENTERESERVAS_SEGUIMIENTODEUNARESERVA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    registrarPerfilDelClienteSchema.add(REGISTRARPERFILDELCLIENTE_CLIENTE, clienteSchema, ObjectSchema.OPTIONAL);
    registrarPerfilDelClienteSchema.add(REGISTRARPERFILDELCLIENTE_AGENTESISTEMA, agenteSistemaSchema, ObjectSchema.OPTIONAL);
    registrarPerfilDelClienteSchema.add(REGISTRARPERFILDELCLIENTE_AGENTECLIENTE, agenteClientesSchema, ObjectSchema.OPTIONAL);
    inscribirHotelesSchema.add(INSCRIBIRHOTELES_AGENTESISTEMA, agenteSistemaSchema, ObjectSchema.OPTIONAL);
    inscribirHotelesSchema.add(INSCRIBIRHOTELES_HOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    inscribirHotelesSchema.add(INSCRIBIRHOTELES_AGENTEHOTEL, agenteHotelesSchema, ObjectSchema.OPTIONAL);
    reservarHotelSchema.add(RESERVARHOTEL_CLIENTE, clienteSchema, ObjectSchema.OPTIONAL);
    reservarHotelSchema.add(RESERVARHOTEL_AGENTESISTEMA, agenteSistemaSchema, ObjectSchema.OPTIONAL);
    reservarHotelSchema.add(RESERVARHOTEL_HOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    reservarHotelSchema.add(RESERVARHOTEL_AGENTEHOTEL, agenteHotelesSchema, ObjectSchema.OPTIONAL);
    registrarCaracteristicasDelHotelSchema.add(REGISTRARCARACTERISTICASDELHOTEL_AGENTESISTEMA, agenteSistemaSchema, ObjectSchema.OPTIONAL);
    registrarCaracteristicasDelHotelSchema.add(REGISTRARCARACTERISTICASDELHOTEL_HOTEL, hotelSchema, ObjectSchema.OPTIONAL);
    registrarCaracteristicasDelHotelSchema.add(REGISTRARCARACTERISTICASDELHOTEL_AGENTEHOTEL, agenteHotelesSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
